name: Linux 构建
on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  build:
    runs-on: matrix.os
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: arm64
    steps:
      - name: 安装工具
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libgtk-3-dev 7zip meson ninja-build

      - name: 设置git
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      
      - name: 获取本仓库文件
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 克隆libui-ng存储库
        run: |
          git clone https://github.com/libui-ng/libui-ng.git --depth 1

      - name: 编译
        run: |
          cd libui-ng
          mkdir -p pkgdir/libui-ng
          meson setup build --prefix=$(pwd)/pkgdir/libui-ng --buildtype=release
          ninja -C build
          ninja -C build install

      - name: 压缩
        run: |
          cd libui-ng/pkgdir

          # 压缩
          7z a -t7z -mx=9 libui-ng-${{ matrix.arch }}.7z "libui-ng"

      - name: 上传
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-${{ matrix.arch }}
          path: |
            libui-ng/pkgdir/libui-ng-${{ matrix.arch }}.7z
          